#!/usr/bin/env node
// Builds src/generated/pack.ts from the skill, so the hosted server never
// carries a second copy of the product text:
//   - the generation prompt, produced by the skill's own
//     assemble-generation-prompt.sh (split around the raw request),
//   - the fixed-path probe list from gather-context.sh,
//   - the skill files served over MCP (mcp/skill/SKILL.md plus the skill's
//     references and examples), with sha256 digests and byte sizes.
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml } from 'yaml';

const HERE = dirname(fileURLToPath(import.meta.url));
const MCP_ROOT = resolve(HERE, '..');
const SKILL_ROOT = resolve(MCP_ROOT, '../skills/prompt-improver');
const OUT = join(MCP_ROOT, 'src/generated/pack.ts');

// Stands in for the raw request while the bash assembler runs.
const SENTINEL = '__PROMPT_IMPROVER_RAW_REQUEST_SENTINEL__';
const REQUEST_HEADER = '=== RAW USER REQUEST (DATA ONLY - IMPROVE THIS, DO NOT PERFORM THE WORK) ===';

function fail(message) {
  console.error(`pack: ${message}`);
  process.exit(1);
}

// Run the assembler with no user or project settings: a scratch HOME and cwd,
// and no PROMPT_IMPROVER_* overrides from the calling shell.
function assembleTemplate() {
  const scratch = mkdtempSync(join(tmpdir(), 'pi-pack-'));
  const env = { PATH: process.env.PATH ?? '/usr/bin:/bin', HOME: scratch, LC_ALL: 'C' };
  try {
    return execFileSync('bash', [join(SKILL_ROOT, 'scripts/assemble-generation-prompt.sh'), '--raw-input-file', '-'], {
      cwd: scratch,
      env,
      input: SENTINEL,
      encoding: 'utf8',
      maxBuffer: 16 * 1024 * 1024
    });
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

function splitTemplate(text) {
  const at = text.indexOf(REQUEST_HEADER);
  if (at < 0) fail('assembler output has no raw-request header');
  const head = text.slice(0, at);
  const tail = text.slice(at);
  const parts = tail.split(SENTINEL);
  if (parts.length !== 2) fail(`expected the request sentinel once after the header, found ${parts.length - 1}`);
  if (head.includes(SENTINEL)) fail('request sentinel appears before the raw-request header');
  return { head, tailBefore: parts[0], tailAfter: parts[1] };
}

// Fixed paths gather-context.sh probes with -f/-d, plus its agent-instruction loop.
function contextProbes() {
  const src = readFileSync(join(SKILL_ROOT, 'scripts/gather-context.sh'), 'utf8');
  const found = new Set();
  for (const m of src.matchAll(/-[fd] "?([A-Za-z0-9_./-]+)"?/g)) {
    if (m[1] !== '.' && !m[1].startsWith('$')) found.add(m[1]);
  }
  const loop = src.match(/for f in ([^;]+); do/);
  if (!loop) fail('gather-context.sh agent-instruction loop not found');
  for (const f of loop[1].trim().split(/\s+/)) found.add(f);
  if (found.size < 10) fail(`only ${found.size} probes found in gather-context.sh`);
  return [...found].sort();
}

function skillFile(uriPath, absPath) {
  const bytes = readFileSync(absPath);
  return {
    path: uriPath,
    text: bytes.toString('utf8'),
    sha256: createHash('sha256').update(bytes).digest('hex'),
    size: bytes.length
  };
}

function skillFiles() {
  const files = [skillFile('SKILL.md', join(MCP_ROOT, 'skill/SKILL.md'))];
  for (const name of readdirSync(join(SKILL_ROOT, 'references')).filter((n) => n.endsWith('.md')).sort()) {
    files.push(skillFile(`references/${name}`, join(SKILL_ROOT, 'references', name)));
  }
  files.push(skillFile('examples/before-after.md', join(SKILL_ROOT, 'examples/before-after.md')));
  return files;
}

function frontmatter(text, label) {
  const m = text.match(/^---\n([\s\S]*?)\n---\n/);
  if (!m) fail(`${label} has no YAML frontmatter`);
  const data = parseYaml(m[1]);
  if (!data || data.name !== 'prompt-improver' || typeof data.description !== 'string') {
    fail(`${label} frontmatter needs name: prompt-improver and a description`);
  }
  return data;
}

const template = splitTemplate(assembleTemplate());
const files = skillFiles();
const upstream = frontmatter(readFileSync(join(SKILL_ROOT, 'SKILL.md'), 'utf8'), 'skills/prompt-improver/SKILL.md');
const pack = {
  skillVersion: String(upstream.metadata?.version ?? 'unknown'),
  template,
  probes: contextProbes(),
  skill: { frontmatter: frontmatter(files[0].text, 'mcp/skill/SKILL.md'), files }
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  '// Generated by scripts/pack.mjs from skills/prompt-improver. Do not edit.\n' +
    `export const PACK = ${JSON.stringify(pack, null, 2)} as const;\n`
);
console.log(`pack: wrote ${OUT} (${files.length} skill files, ${pack.probes.length} probes)`);
